[package]
name = "naive_pseudorandom_generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kolmogorov_smirnov = "1.1.0"
rand = "0.8.5"
